spring:
  application:
    name: InterviewBE

  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DB:testdb}
    username: ${POSTGRESQL_USER:testuser}
    password: ${POSTGRESQL_PASS:testpassword}

